name = "fitforge"
main = "worker.js"
compatibility_date = "2026-02-27"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "fitforge-users"
database_id = "c68cf89a-6b3e-4acd-8dc0-930807d4242d"
